spring.application.name=document-search-backend

server.port=8080

# Danh sách cụm 3 node Elasticsearch phân tán
app.elasticsearch.nodes=http://localhost:9200,http://localhost:9201,http://localhost:9202

# Theo dõi luồng định tuyến và xử lý lỗi
logging.level.com.document.search.document_search_backend=DEBUG